# azure-pipelines-api.yml
trigger:
  branches: { include: [ main ] }

pool:
  vmImage: ubuntu-latest

variables:
  PYTHON_VERSION: '3.10'
  AZURE_SUBSCRIPTION: 'azure-conn'     # <-- your service connection name
  WEBAPP_NAME: 'readmeboost-api'       # <-- your App Service API name
  WORKING_DIR: 'backend'

steps:
- task: UsePythonVersion@0
  inputs: { versionSpec: '$(PYTHON_VERSION)' }

- script: |
    python -m pip install --upgrade pip
    pip install -r $(WORKING_DIR)/requirements.txt
  displayName: Install backend deps

# Package the backend folder to deploy
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: $(WORKING_DIR)
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/backend.zip
    replaceExistingArchive: true

- task: AzureWebApp@1
  displayName: Deploy API to Azure Web App
  inputs:
    azureSubscription: $(AZURE_SUBSCRIPTION)
    appType: webAppLinux
    appName: $(WEBAPP_NAME)
    package: $(Build.ArtifactStagingDirectory)/backend.zip
